version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9999:9999
    volumes:
      - type: bind
        source: ./app
        target: /app
        consistency: delegated # par défaut